services:

  web:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
  

  client:
    build:
      context: ./www/client
      dockerfile: Dockerfile
    container_name: client
    volumes:
      - ./www/client:/www/client
      - /www/client/node_modules
    command: "npm run dev -- --host 0.0.0.0"


  server:
    build:
      context: ./www/server 
      dockerfile: Dockerfile
    container_name: server
    volumes:
      - ./www/server:/usr/src/server
      - /usr/src/server/node_modules
    command: npm run dev


  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    volumes:
      - ./mongodb:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345

