services:
  web:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    cpus: 0.5

  client:
    build:
      context: ./www/client
      # dockerfile: Dockerfile.prod
      dockerfile: Dockerfile.local
    container_name: client
    volumes:
      - ./www/client:/www/client:cached
      - /www/client/node_modules
    environment:
      PORT: 5173
    # command: "npm run start"
    command: "npm run dev -- --host 0.0.0.0 --port 5173"
    cpus: 0.5

  server:
    build:
      context: ./www/server
      # dockerfile: Dockerfile.prod
      dockerfile: Dockerfile.local
    container_name: server
    volumes:
      - ./www/server:/usr/src/server:cached
      - /usr/src/server/node_modules
    # command: "npm run start"
    command: "npm run dev"
    cpus: 0.5

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    volumes:
      - ./mongodb:/data/db:delegated
    cpus: 0.5
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345
