#PROD
# Use official Node.js image as base
FROM node:lts

# Set working directory inside the container
WORKDIR /www/client

# Copy only package manifests, install deps
COPY package.json package-lock.json ./
RUN npm install

# Copy source & build
COPY . .
RUN npm run build && \
    npm prune --production

ENV PORT=5173
CMD ["npm","run","start"]