#LOCAL
FROM node:lts-alpine

# Set working directory inside the container
WORKDIR /usr/src/server

# Copy package.json and package-lock.json first (if available)
COPY package*.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy all source code into container
COPY . .

# Run the application
CMD ["npm", "run", "dev"]
